### ISSUE TITLE
Build instructions for the app

### ISSUE THREAD

**Issue by SandySingh** [flowmodor/flowmodor#1]
Can we add build instructions for the app for people who want to contribute to this project?

**Comment by m4xshen** [comment]
Thanks for the feedback! I'll add the docs about self hosting Flowmodor after I finish the basic features.

**Comment by m4xshen** [comment]
Build instructions and required environment variables are now documented in the [README](https://github.com/flowmodor/flowmodor#development). If you encounter any issues during setup, please feel free to open a new issue!
