### ISSUE TITLE
Desktop app

### ISSUE THREAD

**Issue by m4xshen** [flowmodor/flowmodor#18]
### Discussed in https://github.com/flowmodor/flowmodor/discussions/14

<div type='discussions-op-text'>

<sup>Originally posted by **ExtF8** February 14, 2024</sup>
Thank you for the great application.
I would like to have it as a desktop app as it would be more convenient for me. Therefore, I am planning to undertake that task. I intend to use Electron.js to build a package and publish it to the Snap Store for Ubuntu. If anyone else is interested.
</div>

**Comment by Github11200** [comment]
Would Tauri not be a better choice possibly because it is faster and more resource efficient?

**Comment by m4xshen** [comment]
@ExtF8, following up on the mention of Tauri as a potentially faster, more resource-efficient alternative. Could be an interesting option to consider. Of course, the decision on whether to explore this or continue with Electron.js is all yours.

**Comment by ExtF8** [comment]
At one point I was considering using Tauri, however, in the end, I decided to use Electron.js as I am more familiar with it. But perhaps it would be a good challenge to try out Tauri.

**Comment by m4xshen** [comment]
Flowmodor can now be [installed as PWA](https://x.com/flowmodor/status/1791821742538920019). Therefore I think there's no need for native desktop app.
