### ISSUE TITLE
Contributors?

### ISSUE THREAD

**Issue by bosblaket** [flowmodor/flowmodor#2]
I like what you are building and the concept encouraged me to research the Flowtime Technique.  Are you looking for maintainers and/or contributors to help move the project forward?  I was able to install the app locally today but did come across some updates that can be made to the install instructions.   One missing step I came across is the need to have Docker or another containerization app running prior to step 4 "npx supabase start." Depending on your goal with the app, I'd be happy to help further develop the application and documentation.

**Comment by m4xshen** [comment]
Absolutely, your contribution is greatly appreciated! For the updates and suggestions you mentioned, feel free to create a pull request.
I'm aiming to build an open-source SaaS with this app, and I'll be listing some reported issues on GitHub soon. This way, contributors like you can easily find and work on improvements. Looking forward to your input and collaboration!

**Comment by m4xshen** [comment]
I just add [CONTRIBUTING.md](https://github.com/flowmodor/flowmodor/blob/main/CONTRIBUTING.md). Thanks for your feedback!
