### ISSUE TITLE
Stats show more than 60 min focus time for an hour?

### ISSUE THREAD

**Issue by CookieBoss03** [flowmodor/flowmodor#22]
Hello, 

I've had this issue today, as seen in the below image. I don't really know what that means or how that happened, but i most definitely didn't work more than 60 min in an hour haha. Good luck :)

![stats_2024-03-06T08 21 12 521Z](https://github.com/flowmodor/flowmodor/assets/27889829/0744184a-d913-46f7-9bfc-87bbe13f3956)

**Comment by m4xshen** [comment]
@CookieBoss03 could you provide your email registered on Flowmodor? I'll take a look at the backend data of your stats.

**Comment by CookieBoss03** [comment]
Works now! Thanks a lot :)
