### ISSUE TITLE
Add tooltip for long task name

### ISSUE THREAD

**Issue by m4xshen** [flowmodor/flowmodor#3]
When cursor hover on long tasks name inside the task selector, there should popup a tooltip to display the whole string.

This should be implemented with the [Tooltip](https://nextui.org/docs/components/tooltip) component of NextUI.

<img width="400px" src="https://github.com/flowmodor/flowmodor/assets/74842863/4a17d927-66cf-4600-bb7e-1abb515bde0c" />

**Comment by amelia2802** [comment]
Hi there @m4xshen,

I'm interested in working on this issue! Before I get started, I have a couple of questions for more clarification. Specifically:

- What are the constraints on the design?
- Are there any design patterns, styles, or themes the popup/task list already uses that I should be aware of?

I'm looking forward to working on !

**Comment by m4xshen** [comment]
It's great to hear that you're interested in tackling this issue! Regarding your questions:
- Make sure to use the [Tooltip](https://nextui.org/docs/components/tooltip) component from NextUI.
- The background color should be the same as the dropdown task list (#131221).

**Comment by amelia2802** [comment]
Alright, then I will start to work on this and let you know if I need more clarification or feedback.

**Comment by m4xshen** [comment]
You need to follow the step 4. and 5. in this [doc](https://github.com/flowmodor/flowmodor/blob/main/CONTRIBUTING.md#development).

**Comment by amelia2802** [comment]
Hi @m4xshen , I encountered some authentication issues while running the application on my local machine. Specifically, I received an alert when attempting to sign up as a test user to join a waitlist. Does the database contain any pre-stored test users I can use to log in to the site?
![Screenshot (38)](https://github.com/flowmodor/flowmodor/assets/49182604/c05e211e-c824-4720-a7be-70bbfd78c704)

![Screenshot (36)](https://github.com/flowmodor/flowmodor/assets/49182604/ceabd2a5-8877-4c2a-85cf-91be7c2e0c21)

**Comment by m4xshen** [comment]
@amelia2802 You can create a user at [Authentication tab](http://127.0.0.1:54323/project/default/auth/users) and then login with it.

**Comment by amelia2802** [comment]
Hi @m4xshen , 
![error](https://github.com/flowmodor/flowmodor/assets/49182604/99e88abf-b751-456b-a451-9591ce25f90b)
while creating a new user I'm getting this error;

**Comment by m4xshen** [comment]
@amelia2802 Please run `npx supabase db reset` and then try again.

**Comment by amelia2802** [comment]
Hi @m4xshen , here's the final result
![Screenshot (2)](https://github.com/flowmodor/flowmodor/assets/49182604/ed520e1c-53ab-47f5-bc77-df762c973c99)

Do I need to modify/add anything? or create the pr?

**Comment by m4xshen** [comment]
Yes you can create a pr!
