### ISSUE TITLE
[Bug] Timer UI Overflow on Mobile View

### ISSUE THREAD

**Issue by 1chooo** [flowmodor/flowmodor#31]
### Description
In the mobile app's "Timer" section, the timer display is misaligned and positioned outside of the visible window, causing part of the UI to be cut off. This impacts the user experience as the timer is a core feature of the app, and users might not be able to view the entire timer display correctly. 

#### Expected Behavior

The timer should be fully visible and centered within the app's window, regardless of the device screen size.

#### Steps to Reproduce
1. Open the app on a mobile device.
2. Observe that the timer is not properly centered and overflows outside the screen.

### Screenshots

<img src="https://github.com/user-attachments/assets/e1c43c67-d605-4380-bcfe-2ee5aac5fdc3" alt="Image description" width="200">

### Environment

- Iphone 11
- iOS Version: `17.6.1`

If yes, I can help with this issue.

**Comment by m4xshen** [comment]
@1chooo Thanks for the bug report. It will be fixed in the next update (waiting for Apple review).

**Comment by m4xshen** [comment]
@1chooo You can now update to the latest version!

**Comment by 1chooo** [comment]
> @1chooo You can now update to the latest version!

Thanks!!!
