### ISSUE TITLE
[Feature] Support `Select a List` in Mobile Mode

### ISSUE THREAD

**Issue by 1chooo** [flowmodor/flowmodor#32]
### Description

In the web app, we can select a list to track how much time we spend concentrating. However, in the mobile version, the selection feature is not yet available. It might be a good idea to add this functionality to the mobile mode.

### Suggested Behavior

We could implement this by showing a pop-up window or list to select from when clicking on the 'Focus' button!"

### Screenshots

<img src="https://github.com/user-attachments/assets/e1c43c67-d605-4380-bcfe-2ee5aac5fdc3" alt="Image description" width="200">

### Environment

- Iphone 11
- iOS Version: `17.6.1`

**Comment by m4xshen** [comment]
Thanks for the feedback. The task list related features will be added in the future!

**Comment by m4xshen** [comment]
@1chooo You can now select task from task list in mobile app! Update to latest version to get this feature.

**Comment by 1chooo** [comment]
It works! Thanks @m4xshen
