### ISSUE TITLE
[Bug] Time record not sync between web and mobile

### ISSUE THREAD

**Issue by 1chooo** [flowmodor/flowmodor#34]
The record of time didn't sync up between with the website and the website

> [!NOTE]
> I've make sure using the same account to login
### Screenshots

| Phone | Website |
| -- | -- |
| <img src="https://github.com/user-attachments/assets/db9d5b8f-11a1-4c0a-a07e-65743ab54248" alt="Image description" width="300"> | <img width="1280" alt="Screenshot 2024-09-29 at 7 48 47 PM" src="https://github.com/user-attachments/assets/ca73b4a3-009b-4bd5-ab44-6e5ad1be6a51" width="300"> |

### Environment

phone:

- Iphone 11
- iOS Version: `17.6.1`

website:

- MacOS
- MacOS Version: `14.6.1 (23G93)`

Browser: 

- Brave Version 1.70.117
- Chromium: 129.0.6668.59 (Official Build) (x86_64)

**Comment by m4xshen** [comment]
Hi @1chooo, did you try restart the mobile app?

**Comment by 1chooo** [comment]
> Hi @1chooo, did you try restart the mobile app?

@m4xshen I've tried three times, and it's still not showing up; therefore, I launch this issue.

**Comment by 1chooo** [comment]
Sorry that it's coming now... It's not the bug. 

![image](https://github.com/user-attachments/assets/e0f0b9b2-eea9-49f8-98c9-6f21314f5650)

**Comment by m4xshen** [comment]
Great! No worries.
