### ISSUE TITLE
Count up flow timer possible?

### ISSUE THREAD

**Issue by ronilaukkarinen** [flowmodor/flowmodor#36]
I prefer flow timers that count from 0:00:00 to infinity. Is this possible with Flowmodor?

**Comment by m4xshen** [comment]
Hi @ronilaukkarinen, Flowmodor currently counts up until you stop it in the focus session. Is this what you want? If not please explain more about it.

**Comment by ronilaukkarinen** [comment]
Oh, I didn't realize this. Thanks.

Can you filter by Project?

**Comment by m4xshen** [comment]
The projects should be available in the list like this:

![36CCB319-F268-4E9C-AC06-23C9F6B2FAC1_1_201_a](https://github.com/user-attachments/assets/ed6ec7f1-aef7-43d9-a47c-4488d2e202af)
