### ISSUE TITLE
Suggestions for Timer Reset Button and Improved Page Navigation in Focus Mode

### ISSUE THREAD

**Issue by virignia-w** [flowmodor/flowmodor#38]
Hi! I recently started using Flowmodor, and I wanted to share a couple of minor suggestions based on my experience.

1. Page Navigation in Focus Mode: I noticed that when I’m in focus mode and try to open the account page (or similar sections), the page opens in the same tab, which resets the focus timer. This has happened a few times, disrupting my focus sessions. If possible, would you consider opening these pages in a new tab by default? I think this could help prevent accidental timer resets.

2. Timer Reset Button: At the end of the day, I stop the focus timer, which then switches to the break period. However, each morning, I need to refresh the website to reset the focus timer. It’s not a major issue, but a reset button might make it easier for users to restart the clock without refreshing the page.

Thank you very much for considering these suggestions! I appreciate the effort you put into Flowmodor, and I’m excited to keep using it.

**Comment by m4xshen** [comment]
Hi @virignia-w, both issues are now resolved:

1. Page navigation now opens a new tab if timer is currently running.
2. A reset button is added for user to skip break session.

Thanks for the great suggestions! You can refresh website to use the latest version.
