### ISSUE TITLE
Timer image overlaps with hero image on landing page

### ISSUE THREAD

**Issue by 1chooo** [flowmodor/flowmodor#39]
### Description:
I noticed that the top section of the Flowmodoro Timer overlaps with the demo banner when using the Brave browser. However, when resizing the browser window, space appears correctly between the banner and the Flowmodoro Timer component.

It seems that the alignment issue is inconsistent and might depend on the browser size or resolution.

### Screenshots:

<img width="1280" alt="Screenshot 2024-11-22 at 3 13 28 PM" src="https://github.com/user-attachments/assets/bb38bc55-c708-42b3-9fa3-8b1e6e7f2d90">

<img width="1392" alt="Screenshot 2024-11-22 at 3 18 27 PM" src="https://github.com/user-attachments/assets/f284b56d-fc42-4a4e-bd22-432cc29fe9ee">

<img width="1392" alt="Screenshot 2024-11-22 at 3 18 49 PM" src="https://github.com/user-attachments/assets/898e8e6d-8fbb-4a2d-a08a-71ea4f2ddd44">

Browser Details:
- **Browser:** Brave
- **Version:** 1.73.89 Chromium: 131.0.6778.69 (Official Build) (x86_64)

Please confirm if this behavior is intended or if an adjustment is needed. If this is not a bug, feel free to disregard this feedback. Thanks @m4xshen

**Comment by m4xshen** [comment]
Thanks for reporting this issue. Yeah, there should have a space between them. This issue happens when the scale is more than 125%.

**Comment by 1chooo** [comment]
If I change the `width` of the browser to 1024px, it may result in this bug. Therefore, I think the problem is between the [1024, 1440] because there is no problem in `1440px`.

<img width="1280" alt="Screenshot 2024-11-22 at 3 22 15 PM" src="https://github.com/user-attachments/assets/32409433-7df6-4fc8-9c06-1f99e49a51f5">

**Comment by m4xshen** [comment]
Thanks for the detail testing. If you’re willing to submit a PR to solve this, it’d be greatly appreciated, but no pressure at all.

**Comment by 1chooo** [comment]
> Thanks for the detail testing. If you’re willing to submit a PR to solve this, it’d be greatly appreciated, but no pressure at all.

Sure, I can try this, but maybe require some time to research how to solve it! I'll fork at first.

**Comment by m4xshen** [comment]
> prefer the code base of the first one because we don't have to add the <style> in our code

I agree. However it seems that the second one still has some issues when scale is set to 150% on Chrome:

https://github.com/user-attachments/assets/2cdb861f-d8b8-45d7-a0ec-13add11bc823

Btw can ResponsivelyApp set the scale of each browser? I only find the `Zoom` setting, but it is the scale of the whole app not the actual browser scale.

**Comment by 1chooo** [comment]
I also could not find the `scale` option for ResponsivelyApp, I only used scale from my browser. 

You are right, I find this problem when we scale to the `150%`, and it seems like the first solution won't affect this situation. The first is perfectly solve this problem, only the space between `Hero` and `Features` will magnify. However, I find the space between `Hero` and `Features` is the same as each of `Features`.

> > prefer the code base of the first one because we don't have to add the <style> in our code
> 
> I agree. However it seems that the second one still has some issues when scale is set to 150% on Chrome:
> 
>  Screen.Recording.2024-11-22.at.5.10.36.PM.mov 
> Btw can ResponsivelyApp set the scale of each browser? I only find the `Zoom` setting, but it is the scale of the whole app not the actual browser scale.

I also could not find the `scale` option for ResponsivelyApp, I only used scale from my browser. 

You are right, I find this problem when we scale to the `150%`, and it seems like the first solution won't affect this situation. The first code base is perfectly solve this problem, only the space between `Hero` and `Features` will magnify in the original `100%`. However, I find the space between `Hero` and `Features` is the same as each of `Features`. So, maybe it is still accepted!?

**Comment by 1chooo** [comment]
Hi @m4xshen 

I have found the other solution, I will define the config in the `tailwind.config.mjs`. Add custom definition of `xlg` to handle the screen larger than `1440px`.

```diff
const defaultTheme = require('tailwindcss/defaultTheme');

/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  theme: {
    colors: {
      primary: '#DBBFFF',
      secondary: '#23223C',
      background: '#131221',
      white: '#FFFFFF',
    },
    extend: {
      boxShadow: {
        custom: '-25px -25px 30px -15px rgba(0, 0, 0, 0.25)',
      },
+       screens: {
+         'xlg': '1440px',
+       },
    },
    fontFamily: {
      sans: ['Inter Variable', ...defaultTheme.fontFamily.sans],
    },
  },
  plugins: [require('@tailwindcss/typography')],
};
```

```diff
<div
  id="features"
-   class="relative gap-40 mb-60 sm:my-60 flex w-full flex-col items-center px-3 text-center lg:text-start"
+   class="relative gap-40 mb-60 sm:my-60 flex w-full flex-col items-center px-3 text-center lg:text-start lg:mt-[25rem] xlg:mt-[15rem]"
>
```

https://github.com/user-attachments/assets/12e402e3-5ee1-469e-8ecb-132425266fea
