### ISSUE TITLE
Allow user undo completeting task

### ISSUE THREAD

**Issue by m4xshen** [flowmodor/flowmodor#4]
When task is marked as completed, a toast should appear with a message "Task XXX completed" and a button of undo option.

The UI should be implemented with `react-toastify` and `@nextui-org/button`.

**Comment by toreis-up** [comment]
Hi @m4xshen san.

I'd like to work on this issue if you haven't done any work yet.
I have read some codes, It might be some breaking change...

**Comment by m4xshen** [comment]
@toreis-up  Sure you can work on it! Feel free to ask any question.

**Comment by toreis-up** [comment]
I have roughly implemented it. you can check it out at toreis-up/feat/toast-complete. (Or should I create pr?)

I also have a few questions.
1. after checking a checkbox, should the element remain on the screen until it is fetched again?
2. what is the position of the toast? Currently, it is set to the top right of the screen which is the default.

Please feel free to ask for any changes.

**Comment by m4xshen** [comment]
You can open a pull request after making the following changes:
1. `react-toastify` is already installed and setup, so there's no need to install it. You can just use:
```javascript
import { toast } from 'react-toastify';
````
The position and styling will automatically applied on it.
2. After checking the checkbox the task should disappear just like the original behavior.
3. The order doesn't matter.

**Comment by toreis-up** [comment]
1, 3: oh, I missed out. ok, thank you :)

2:
https://github.com/flowmodor/flowmodor/blob/dfd852022d920624dea9d1566ce52d6ae5324c12/src/stores/useTasksStore.ts#L37
In this code, it ignore fetch after undo, and it's required to reload to fetch completely.
it doesn't matter?

**Comment by m4xshen** [comment]
Ah, you can add an `else` part to append the task if it is undo and added into the list.
