### ISSUE TITLE
"Share stats!" Button not work in web mode

### ISSUE THREAD

**Issue by 1chooo** [flowmodor/flowmodor#44]
When we visit the `/stats` and click the share button, the workflow of sharing is great. It shows the loading effect and the badge of the successful status. However, when we want to paste the sharing content, it is not work (cmd + c or right-click). 

Also, once we have clicked the share button the hover effect stays hovered even waiting the time, it still shows on the screen. We maybe need to check the hover effect, either.

### Screenshots

https://github.com/user-attachments/assets/6f3a2b2e-9667-4d4f-9d36-7373f9dc8836

**Comment by m4xshen** [comment]
Hi @1chooo, where did you paste the image to? It should work on most of the platform.

**Comment by 1chooo** [comment]
> Hi @1chooo, where did you paste the image to? It should work on most of the platform.
> 
> As for the tooltip, I'll make it disappear after sharing. Thanks for the suggestion.

Hi! I tried pasting the code into the search box in the Browser and the editorin VSCode, but it seems like it's meant to be used as a URL or something similar. Could you help me understand where exactly I should paste it or how to use it properly?

**Comment by m4xshen** [comment]
Here's an example of how to use it:

https://github.com/user-attachments/assets/32791b85-e9da-4a93-a871-cb21f9d585d8

You can also paste into Linkedin, Discord, Messenger, etc. I think most of the social media and messaging app supports this.

Maybe I should make the prompt clearer so that users don't get confused.
