### ISSUE TITLE
[Urgent] web app crashes if selected task is deleted

### ISSUE THREAD

**Issue by arjun6757** [flowmodor/flowmodor#49]

**Comment by m4xshen** [comment]
It should be fixed now. Thanks for the quick report.

**Comment by arjun6757** [comment]
@m4xshen i thought you wanted select component to be taking a larger space than the one you are using now...honestly it looks a bit of cramped now 😁what do you think ? .... btw before reporting this issue i was fixing my own code and now it is more of a custom component that is sending clicks to the nextui select although the alignment might be a bit loss (only a bit) but didn't commit it due to the FocusingTask.tsx deletion and merge conflicts

**Comment by m4xshen** [comment]
> it looks a bit of cramped now

Do you mean the width of the select items list?

**Comment by arjun6757** [comment]
Yeah but it's not that much of a issue.

**Comment by m4xshen** [comment]
The width is adjusted now.

**Comment by arjun6757** [comment]
@m4xshen it looks much better now.
