### ISSUE TITLE
Pause Functionality

### ISSUE THREAD

**Issue by m4xshen** [flowmodor/flowmodor#9]
### Discussed in https://github.com/flowmodor/flowmodor/discussions/7

<div type='discussions-op-text'>

<sup>Originally posted by **bosblaket** January 23, 2024</sup>
What are your thoughts on adding the ability to pause a running timer?  The user could pause the running timer in the event of an interruption, then press play to continue the timer when they resume work.  Currently if I'm interrupted and I hit stop, i'm forced to the break timer, although i'd prefer to continue the existing timer in certain situations when i have a brief interruption. </div>

**Comment by the-halfbloodprince** [comment]
@m4xshen Are you working on this issue? if not so I'd like to give it a shot

**Comment by m4xshen** [comment]
@the-halfbloodprince  No I'm not. You can go ahead!

Make sure to:
- only allow pause function at focus mode (it doesn't make sense in break mode)
- [log](https://github.com/flowmodor/flowmodor/blob/main/src/hooks/useLog.ts) the session when user pressed pause
- use this [font awesome svg](https://fontawesome.com/icons/pause?f=classic&s=solid) for the pause icon

**Comment by the-halfbloodprince** [comment]
Sure @m4xshen got it

**Comment by m4xshen** [comment]
@the-halfbloodprince I just got a user's feedback:
```
A pause feature would be great. Quite often during the break part I will have a colleague come up to me, ask for help and take me away from that 5 minute break I had. If I could instead pause the break (and the working clock), it'd be a great simple feature
```

So I think that there's also need to pause the break timer. Therefore I decided to allow the pause feature at break mode. Could you please implement pause function both at focus mode and also break mode.

**Comment by the-halfbloodprince** [comment]
Yeah that makes sense. Sure, I'll add it on both the modes. Also apologies, got a shit ton or work just after taking this up, should have done it by now else

**Comment by the-halfbloodprince** [comment]
@m4xshen I had to reclone the repo yesterday after some issues on my device. I'm having issues starting supabase up. I followed the steps again as in CONTRIBUTING.md.

On step 5 (npx supabase start) `supabase_pg_meta_flowmodor` throws this error for me:
![image](https://github.com/flowmodor/flowmodor/assets/55590289/658ace01-d27a-44a0-82f0-50ae6b67d4a2)

I tried figuring it out but it wasted quite some time already. Do you have any idea or suggestions?

**Comment by m4xshen** [comment]
@the-halfbloodprince What's the output of running `npx supabase status`?

**Comment by the-halfbloodprince** [comment]
The containers just exited after the error
![image](https://github.com/flowmodor/flowmodor/assets/55590289/50d6a45b-c655-421e-aeb3-fa6fbe7808a2)

**Comment by m4xshen** [comment]
Please try  `npx supabase start --ignore-health-check` and see whether it works.

**Comment by the-halfbloodprince** [comment]
@m4xshen Seems to work for now. The containers didn't terminate automatically, though the db is still inaccessible but that's fine for now, I'll try to add the feature in the frontend till then

**Comment by the-halfbloodprince** [comment]
@m4xshen how do you suggest the UI should be? just a pause/play button alongside a stop/play button may seem confusing. For eg, there can be times the user accidentally out of habit clicks the "stop" button and then his break starts and then again it's a mess.

I think the usual traditional way of playing tracks will make more sense. Like:

- ## Stopped State: when the user has not even started the task, there must be just two buttons:
  - hide time button
  - start the timer button

    ![image](https://github.com/flowmodor/flowmodor/assets/55590289/6694f30a-8e5d-4262-b5de-c67d5efd3635)

- ## Running State: after the user starts, there must be:
  - hide time button
  - pause the timer button

    ![image](https://github.com/flowmodor/flowmodor/assets/55590289/15f0158b-3fe8-41c5-9dc8-3fe30af6919b)

- ## Paused State: once the user pauses the timer, then there must be3 buttons:
  - hide time button
  - resume (play) the timer button
  - stop the time button 

    ![image](https://github.com/flowmodor/flowmodor/assets/55590289/e2aff7f9-8ca9-4636-8881-32a6a36cd742)

    or, to prevent more accidental "stop"s, a red button:

    ![image](https://github.com/flowmodor/flowmodor/assets/55590289/da0450cb-f7f7-4aa3-b37e-14fdf017e0a4)

**Comment by m4xshen** [comment]
Your ideas are good overall, but the Running State should also contain a stop button. Here's the summary with the flow after each button is pressed:

![5CDA95FA-9F71-4436-90EC-E896979A4187](https://github.com/flowmodor/flowmodor/assets/74842863/64b79c78-c815-4e83-93e4-c7cb77c47c22)

As for the issue of accidental stop, I prefer to pop a modal for user confirming to stop instead of a red button.

**Comment by m4xshen** [comment]
@the-halfbloodprince Since it's been a long time since the last discussion, I took the task and have now finished it. Hope you don't mind.

**Comment by the-halfbloodprince** [comment]
Hey @m4xshen sure man thanks 🙌 I genuinely got too busy due to unforeseen difficulties. I was planning on either finding some time and finishing it or just letting you know that it's gonna take some time for me and instead of wasting the time, you can implement it yourself. Anyways, thanks for doing it yourself. Will be contributing meaningfully next time for sure. 🙌
